platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'Mall' do

  pod 'CYLTabBarController', '~> 1.28.1'
  pod 'SnapKit', '~> 4.2.0'
  pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher', '~> 4.10.1'
  pod 'SwiftyJSON', '~> 5.0.0'
  
  target 'MallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MallUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
