platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'Mall' do

  pod 'CYLTabBarController', '~> 1.28.1'
  pod 'SnapKit', '~> 4.2.0'
  pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher', '~> 4.10.1'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'SDCycleScrollView', '~> 1.80'
  pod 'IQKeyboardManagerSwift'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'MJRefresh', '~> 3.1.16'
  pod 'TYPagerController', '~> 2.1.2'
  pod 'KeychainSwift', '~> 16.0.1'
  
  target 'MallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MallUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
